manifest:
  remotes:
    # 定义一个名为 ncs 的远程源，指向 nrfconnect 的 GitHub
    - name: nrfconnect
      url-base: https://github.com/nrfconnect

  projects:
    - name: sdk-nrf
      remote: nrfconnect
      # 锁定使用的 NCS SDK 版本
      revision: v2.9.0
      path: nrf
      # 'import: true' 会导入 sdk-nrf 文件中定义的所有依赖项 (zephyr, etc.)
      import: true

  # 本项目自身
  self:
    path: .
