name: NCS Build CI

on:
  push:
    branches: [ master ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        board: ['nrf52840dk/nrf52840']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install west
        run: pip3 install west

      - name: Setup Zephyr projects
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: .
          toochains: arm-zephyr-eabi
          sdk-version: 0.16.4

      - name: Export Zephyr Cmake package
        run: |
          west zephyr-export
          
      - name: Build for ${{ matrix.board }}
        run: |
          west build --pristine -b ${{ matrix.board }} -d build/${{ matrix.board }} .

      - name: Upload firmware as artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/${{ matrix.board }}/merged.hex 

  flash_and_check:
    needs: build
    runs-on: [self-hosted]
    strategy:
      matrix:
        board: ['nrf52840dk/nrf52840']
    steps:
      - name: Download firmware
        uses: actions/download-artifact@v4
        with: 
          name: firmware
          path: ./firmware

      - name: Flash firmware
        run: |
          ls ./firmware
          sudo nrfjprog -i
          sudo nrfjprog --recover
          nrfjprog --program ./firmware/merged.hex --chiperase --reset
      
      # - name: Install Python dependencies
      #   run: |
      #     pip install -r blueS/requirements.txt

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: BLECheck
        run: |
          cd blueS
          ls
          ./blues_launcher ble_test
      
      # - name: Upload results
      #   if: ${{ steps.BLECheck.outcome=='success' }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: check results
      #     path: ./res.json